### ISSUE TITLE
[BUG] 直播间room_id超过32767会提示房間無效，已略過 

### ISSUE THREAD

**Issue by bakanico** [iyear/biligo-live#3]
直播间room_id超过int16的范围就会报错

    2021/12/26 17:20:38 房間 3415150 無效，已略過 
    2021/12/26 17:20:38 Resolving Error: *json.UnmarshalTypeError
    2021/12/26 17:20:38 json: cannot unmarshal number 88615 into Go struct field RoomInfoData.data.short_id of type int16
    [GIN] 2021/12/26 - 17:20:38 | 500 |   40.804101ms |       127.0.0.1 | PUT      "/subscribe/add"
    Error #01: json: cannot unmarshal number 88615 into Go struct field RoomInfoData.data.short_id of type int16

**Comment by iyear** [comment]
这是你自己的结构体出问题了吧

**Comment by eric2788** [comment]
> 直播间room_id超过int16的范围就会报错
> 
> ```
> 2021/12/26 17:20:38 房間 3415150 無效，已略過 
> 2021/12/26 17:20:38 Resolving Error: *json.UnmarshalTypeError
> 2021/12/26 17:20:38 json: cannot unmarshal number 88615 into Go struct field RoomInfoData.data.short_id of type int16
> [GIN] 2021/12/26 - 17:20:38 | 500 |   40.804101ms |       127.0.0.1 | PUT      "/subscribe/add"
> Error #01: json: cannot unmarshal number 88615 into Go struct field RoomInfoData.data.short_id of type int16
> ```

你应该是issue发错地方了，那个问题早修了: https://github.com/eric2788/biligo-live-ws/commit/293bc0e8c37928fe43c9219bf56385abcb96664d

@iyear 可以关了
